# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.6
  - 3.5
dist: xenial
sudo: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox

before_deploy:
    - pip install -e .[doc]
    - make docs

# deploy new versions to PyPI / GithubIO
deploy:
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: "G/z8CnMHS1DfvSxZgkqGxH4Wr8yAxyOAGFAtbacXmosCnVLO4GKO7Je1KEgCsGJbQdjpexBaPxDg2SbE9jYCxyAzSim+S91WYeqMkrnyTh8Pmaoxbo8OTkImZYu4t/dcPOkSMH1kPHUOT6vwdlzyBays5EfD3jAnjLV2CEZdH4cr3Rfv3lV8tSF/XC3CSPE9UAyO5NQTW/0EGogQtBaa9/DwsjvnAOeA9azFvr3/nhVbZ/KSVS5A86s/YJiMYeGeIrTFelKXIAFOKrRfU6Jnw7y/LdkFZIwptlsQAnaxsvVvIQOFyW4fz+0UgUDUC39wQvxPwHyc/vVs2CbjaO/OFFDdqb9SaP4ZuwGQPXFzNL7FJSoIc0EIZZ2gLA26pWD47SbJI74mZpoxEjvVbL1ZozhWRWHuhXkwjTPuV9ewCXKosDPaCxwohU3xdb9rNawpUDstDLePylwuBXyLZz4BJyU3/yYdyXVGwKNJ33LBOHayidsKSfInSuC0I3+Xfw+6zX/fJnrG0GU0EcvkBZ2GoQRe042oyBADtQ2R4tmlhtzn04etbAbXCrb4OYk7onUxSIKFHarIY4ckIwmO2UklTPPoQZ/aIQSBBTV60uHo0C1MSJLduo0ZoRI3gNLfu7ObKB0YWN+PrJAWpCFeWBmxA/utQpQY7zllgYV7hyT0cn4="
    local_dir: docs/build/html
    on:
      branch: master
#      tags: true
#      repo: ucloud/ucloud-sdk-python3
      python: 3.7
  - provider: pypi
    distributions: sdist bdist_wheel
    skip_existing: true
    user: ucloud
    password:
      secure: "NrYxM9Coe8YRBejYtd6Kg32OKkdTFKbW6MKgAUIh4xW58enfnT1f1c/hE+0d1mBcOAR0sfArVIYaqUwz4B7s6QxyBvbHtJ97VThTmDkwx2u0ESq5pGnS2886kKfAODudfmKriCd6gZ8i3wyILriMcf4P8vojpXJ7ZzmbkesgX1fIzDEOJyxpBA/v9RXD+HfoXsAvY05PvgSFHSRZid15R4c+J09GKE2BgqRWLY5q+RKQyANZw8ee/fEl5a3zAMf/MHcB+Bwjv1dh21LWg+WUza2yZWO60E2KNcI5PFxXSiVWPm0xdeFGA9wLEW4QDdugPcjQN2ou+uyHOl9UFcJQ/+/HmYc/TnesZbv1HZkZyWzfBEsM4yrs4FE6Q7QWvL7szSyTyaamLKBaFtMwNzgpCHo1kOD6Lz2ezJRfCJe05d+EBCdxovCdbsRlTwEB2FDXuKRjvqNOJSzCtRpo+dOYz+5NjGq7o9n6yQYpEtQ9YDKm6vF8wFBDjsARG+BmUzGq+jBIY+UQIY+yTsuODS/AdT8jFlO2HkGjcBpV1Kru8Z9hu0NpDcuUvM2XxUvElbLtdS1jEgSBMGhQ7NjPPRKFFRHruL3JnXFEN12ZEi6ccnZmExINtH+hNWJpfFRl/CMBMqbtLhQh2qi4qJktQoEHgFoDWDUe9jXQk1v8TqraHps="
    on:
      branch: master
#      tags: true
#      repo: ucloud/ucloud-sdk-python3
      python: 3.7
