# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.6
  - 3.5
dist: xenial
sudo: true

env:
    global:
        secure: "0vITN4tv7GHlXKzx5Q+2n2MrzpfAQgeuf6fiD6JyO48VsvX6S/ExaCQJUuoU9xgov+UQ2bHb5SHNStOFjrJgpAAmktH7HMCEt8CYZUi5mqG2t2e8Gu6pDMZcA0DW3U7K2dYq5ka3LvIcZI6RrLlDpx7/hHkgGJKIjSVTi6hHyjs9KZCXbzl8RoDRmSgmD8CFYskKn4/yEVyaj1fz6q7l9chbpb04WSzZLj9h3J65efY8JQ3h9s5i8JIvAJ+PPP4Qpvfge/1dd5VOrDB9ppWbTx67Swy1p+DZh6Q/qa7L873Tmhmi53tTo6Q+a6eBea2cnevt1cwxsjRVcNwRwEZGoCrqDiL23y6GMI0sAx83tS3CAuuNufI/f2bdhGpnwPa+hx1PlP31JAnAaUkSIKf74WoVeNAxSJ+bY1acpaHzpOtL95cYhaD9dL8Iu+HaTBV1Vxq9x58ozB62wcalZ+P/rMa6rsswWI1zyznwiUDbU3HHG63BZOqpAwdpH1IA8Am+G0wfREvr1+ICpbjtKalgr0wT/v3fM7ScsTozT2tTj/b6RwbXsfeDoy+TMqt+P3PiJeqALqqv9k7cbfMQEadw8e6zTns7IfMO5LktP1Cb6ALcMqhgDP6dd5g+aqMl5wj/QQg9ImUYVZvZm5nb5iLvtKjkIDebmrUdRGUtO6aw9Jk="

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox

before_deploy:
    - pip install -e .[doc]
    - make docs
    - ls docs/build/html
    - echo ${TEST}
    - echo ${GITHUB_TOKEN:0:5}

# deploy new versions to PyPI / GithubIO
deploy:
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: $GITHUB_TOKEN
    local_dir: docs/build/html
    on:
      branch: master
#      tags: true
#      repo: ucloud/ucloud-sdk-python3
      python: 3.7
  - provider: pypi
    distributions: sdist bdist_wheel
    skip_existing: true
    user: ucloud
    password:
      secure: $PYPI_PASSWORD
    on:
      branch: master
#      tags: true
#      repo: ucloud/ucloud-sdk-python3
      python: 3.7
