# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.6
  - 3.5
dist: xenial
sudo: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -e .[ci]

# command to run tests, e.g. python setup.py test
script:
    - make lint
    - make test-cov

after_success:
    - bash <(curl -s https://codecov.io/bash)
