""" Code is generated by ucloud-model, DO NOT EDIT IT. """

import typing


from ucloud.core.client import Client
from ucloud.services.uhids.schemas import apis


class UHIDSClient(Client):
    def __init__(
        self, config: dict, transport=None, middleware=None, logger=None
    ):
        super(UHIDSClient, self).__init__(config, transport, middleware, logger)

    def add_uhost_sec_base_check_white_rule(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """AddUHostSecBaseCheckWhiteRule - 添加安全基线白名单

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_
        - **Data** (str) - (Required) 基线白名单规则信息（值为以下字段的json转base64后字符串，json格式：{"Data":[{"IP":{"Type":"ip","IPs":["192.168.3.4","192.168.3.4"]},"RuleID":"B0101001V01","AppName":"Linux","Description":"存在弱口令用户[testUser]","RiskType":"配置缺陷","RiskLevel":"高危","User":"testUser"},{"IP":{"Type":"all","IPs":[]},"RuleID":"B0101001V01","AppName":"Linux","Description":"存在弱口令用户[testUser]","RiskType":"配置缺陷","RiskLevel":"高危","User":"testUser"}]}）

        **Response**

        - **Fail** (int) - 失败数
        - **Success** (int) - 成功数

        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.AddUHostSecBaseCheckWhiteRuleRequestSchema().dumps(d)

        # build options
        kwargs["max_retries"] = 0  # ignore retry when api is not idempotent

        resp = self.invoke("AddUHostSecBaseCheckWhiteRule", d, **kwargs)
        return apis.AddUHostSecBaseCheckWhiteRuleResponseSchema().loads(resp)

    def add_uhost_sec_web_risk_white_rule(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """AddUHostSecWebRiskWhiteRule - 添加webrisk白名单

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_
        - **Data** (str) - (Required) webrisk白名单规则信息（值为以下字段的json转base64后字符串，json格式：{"Data":[{"IP":{"Type":"subnet","IPs":["192.168.1.0/24","172.36.1.0-172.36.255.255"]},"Type":"不安全的配置","RuleId":"30001","RiskDesc":"未删除的.git目录","Detail":"未删除的.git目录，黑客可以直接下载git相关文件","FileName":"/var/www/html/DiscuzX/install/index.php"},{"IP":{"Type":"all","IPs":[]},"Type":"不安全的配置","RuleId":"30001","RiskDesc":"未删除的.git目录","Detail":"未删除的.git目录，黑客可以直接下载git相关文件","FileName":"/var/www/html/DiscuzX/install/index.php"}]}）

        **Response**

        - **Fail** (int) - 失败数
        - **Success** (int) - 成功数

        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.AddUHostSecWebRiskWhiteRuleRequestSchema().dumps(d)

        # build options
        kwargs["max_retries"] = 0  # ignore retry when api is not idempotent

        resp = self.invoke("AddUHostSecWebRiskWhiteRule", d, **kwargs)
        return apis.AddUHostSecWebRiskWhiteRuleResponseSchema().loads(resp)

    def add_uhostsec_common_login_ip(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """AddUhostsecCommonLoginIp - 添加常用登陆Ip

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_
        - **IPs** (str) - (Required) IP白名单列表,多个逗号间隔

        **Response**


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.AddUhostsecCommonLoginIpRequestSchema().dumps(d)

        # build options
        kwargs["max_retries"] = 0  # ignore retry when api is not idempotent

        resp = self.invoke("AddUhostsecCommonLoginIp", d, **kwargs)
        return apis.AddUhostsecCommonLoginIpResponseSchema().loads(resp)

    def add_uhostsec_common_login_location(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """AddUhostsecCommonLoginLocation - 添加常用登录地

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_
        - **Data** (str) - (Required) 登录地址信息（值为以下字段的json转base64后字符串，json格式：{"Data":[{"Country":"中国","Province":"广东","City":"深圳"},{"Country":"中国","Province":"广东","City":"广州"}]}）

        **Response**


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.AddUhostsecCommonLoginLocationRequestSchema().dumps(d)

        # build options
        kwargs["max_retries"] = 0  # ignore retry when api is not idempotent

        resp = self.invoke("AddUhostsecCommonLoginLocation", d, **kwargs)
        return apis.AddUhostsecCommonLoginLocationResponseSchema().loads(resp)

    def agent_os_statistic(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """AgentOSStatistic - 统计当前主机安装哪些系统，并统计各系统安装数

        **Request**

        - **ProjectId** (str) - (Config) 项目ID

        **Response**

        - **Result** (dict) - 见 **OSList** 模型定义

        **Response Model**

        **OSVersion**
        - **Count** (int) - 该版本系统安装主机数
        - **Name** (str) - 系统名称


        **OSInfo**
        - **Count** (int) - 主机数
        - **OSType** (str) - 系统类型
        - **Version** (list) - 见 **OSVersion** 模型定义


        **OSList**
        - **OS** (list) - 见 **OSInfo** 模型定义
        - **Total** (int) - 主机操作系统总数


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.AgentOSStatisticRequestSchema().dumps(d)

        resp = self.invoke("AgentOSStatistic", d, **kwargs)
        return apis.AgentOSStatisticResponseSchema().loads(resp)

    def agent_warnning_statistic(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """AgentWarnningStatistic - 统计总主机数，在线数，离线数，有风险主机数，无风险主机数

        **Request**

        - **ProjectId** (str) - (Config) 项目ID

        **Response**

        - **Result** (dict) - 见 **AgentWarnningStatisticInfo** 模型定义

        **Response Model**

        **AgentWarnningStatisticInfo**
        - **AgentTotal** (int) - 主机总数
        - **Offline** (int) - 离线主机数
        - **Online** (int) - 在线主机数
        - **SafeCount** (int) - 无风险主机数
        - **WarnningCount** (int) - 有风险主机数


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.AgentWarnningStatisticRequestSchema().dumps(d)

        resp = self.invoke("AgentWarnningStatistic", d, **kwargs)
        return apis.AgentWarnningStatisticResponseSchema().loads(resp)

    def buy_bill_point(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """BuyBillPoint - 购买付费点数

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_
        - **AutoBusiness** (bool) - (Required) 是否自动设置企业版(true-是，false-否)
        - **AutoRenew** (bool) - (Required) 是否自动续费(true-是，false-否)
        - **PointNum** (int) - (Required) 购买数量

        **Response**


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.BuyBillPointRequestSchema().dumps(d)

        # build options
        kwargs["max_retries"] = 0  # ignore retry when api is not idempotent

        resp = self.invoke("BuyBillPoint", d, **kwargs)
        return apis.BuyBillPointResponseSchema().loads(resp)

    def del_uhost_sec_base_check_white_rule(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """DelUHostSecBaseCheckWhiteRule - 删除安全基线白名单

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_
        - **WhiteID** (str) - (Required) 基线白名单ID

        **Response**


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.DelUHostSecBaseCheckWhiteRuleRequestSchema().dumps(d)

        resp = self.invoke("DelUHostSecBaseCheckWhiteRule", d, **kwargs)
        return apis.DelUHostSecBaseCheckWhiteRuleResponseSchema().loads(resp)

    def del_uhost_sec_common_login(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """DelUHostSecCommonLogin - 删除常用登陆IP或常用登陆地

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_
        - **Region** (str) - (Config) 地域。 参见  `地域和可用区列表 <https://docs.ucloud.cn/api/summary/regionlist>`_
        - **WhiteID** (str) - (Required) 登录白名单ID
        - **Zone** (str) - 可用区。参见  `可用区列表 <https://docs.ucloud.cn/api/summary/regionlist>`_

        **Response**


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
            "Region": self.config.region,
        }
        req and d.update(req)
        d = apis.DelUHostSecCommonLoginRequestSchema().dumps(d)

        resp = self.invoke("DelUHostSecCommonLogin", d, **kwargs)
        return apis.DelUHostSecCommonLoginResponseSchema().loads(resp)

    def del_uhost_sec_warnings(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """DelUHostSecWarnings - 删除告警

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_
        - **Data** (str) - (Required) 要删除告警的列表json格式：{"Data":[{"WarnType":"WebShellAlarm","ID":"59e870483ef9f419617b7744"},{"WarnType":"checkCockhorse","ID":"59f67a26812c307b65d72e99"}]}）WarnType类型：WebShellAlarm，checkCockhorse，BaseCheck，webRisk,VulCheck2，AbnormalLogin，SshBruteSucceeded

        **Response**


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.DelUHostSecWarningsRequestSchema().dumps(d)

        resp = self.invoke("DelUHostSecWarnings", d, **kwargs)
        return apis.DelUHostSecWarningsResponseSchema().loads(resp)

    def get_uhosts_ec_agent_deployment_statistics(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """GetUHostsecAgentDeploymentStatistics - 获取当前项目制定工程的Agent部署统计值，包括安装与未安装信息

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_

        **Response**

        - **Installed** (int) - 已安装台数
        - **Uninstalled** (int) - 未安装台数

        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.GetUHostsecAgentDeploymentStatisticsRequestSchema().dumps(d)

        resp = self.invoke("GetUHostsecAgentDeploymentStatistics", d, **kwargs)
        return apis.GetUHostsecAgentDeploymentStatisticsResponseSchema().loads(
            resp
        )

    def get_uhosts_ec_agent_install_script(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """GetUHostsecAgentInstallScript - 不同的项目使用的安装脚本附带的属性值会有差异，这里需要根据每个不同的项目来获取相应的主机安全agent安装脚本下载地址

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_

        **Response**

        - **InstallScript** (str) - 安装脚本内容

        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.GetUHostsecAgentInstallScriptRequestSchema().dumps(d)

        resp = self.invoke("GetUHostsecAgentInstallScript", d, **kwargs)
        return apis.GetUHostsecAgentInstallScriptResponseSchema().loads(resp)

    def get_uhosts_ec_base_check_rule_description(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """GetUHostsecBaseCheckRuleDescription - 获取基线检测指定规则详细描述

        **Request**

        - **ProjectId** (str) - (Config) 项目ID
        - **RuleID** (str) - (Required) 规则ID

        **Response**

        - **Description** (str) - 规则描述

        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.GetUHostsecBaseCheckRuleDescriptionRequestSchema().dumps(d)

        resp = self.invoke("GetUHostsecBaseCheckRuleDescription", d, **kwargs)
        return apis.GetUHostsecBaseCheckRuleDescriptionResponseSchema().loads(
            resp
        )

    def get_uhostsec_agent_deployment_situation_with_ver_info(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """GetUhostsecAgentDeploymentSituationWithVerInfo - 获取当前项目的主机安装信息，包括IP，当前付费版本等信息

        **Request**

        - **ProjectId** (str) - (Config) 项目ID

        **Response**

        - **InfoList** (list) - 见 **HostAgentStatusInfo** 模型定义
        - **InstallNum** (int) - 已安装UHIDS的主机数
        - **TotalNum** (int) - 主机总数
        - **UninstallNum** (int) - 未安装UHIDS的主机数

        **Response Model**

        **NIC**
        - **IP** (str) - 网卡ip
        - **Mac** (str) - 网卡mac


        **HostAgentStatusInfo**
        - **AgentId** (str) - UHIDS的Agent识别ID
        - **HostName** (str) - uhost的备注名
        - **Installed** (bool) - 是否已经安装
        - **Ip** (list) - 主机IP列表
        - **NICs** (list) - 见 **NIC** 模型定义
        - **NowVer** (int) - 此主机当前UHIDS版本信息
        - **OsName** (str) - 系统版本
        - **SetVer** (int) - 用户设置此主机UHIDS版本信息
        - **UHostId** (str) - uhost资源短ID
        - **Zone** (str) - 可用区


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.GetUhostsecAgentDeploymentSituationWithVerInfoRequestSchema().dumps(
            d
        )

        resp = self.invoke(
            "GetUhostsecAgentDeploymentSituationWithVerInfo", d, **kwargs
        )
        return apis.GetUhostsecAgentDeploymentSituationWithVerInfoResponseSchema().loads(
            resp
        )

    def get_uhostsec_trojan_description(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """GetUhostsecTrojanDescription - 获取某一类木马告警的详细描述信息

        **Request**

        - **ProjectId** (str) - (Config) 项目ID
        - **TableName** (str) - (Required) 获取指定当前木马对应的告警表名，指定当前木马对应的告警表名，利用告警表名来获取当前的描述信息,可以通过获取ListUHostsecTrojanWarnsResponse的返回信息提供TableName值内容，值：WebShellAlarm、checkCockhorse

        **Response**

        - **Description** (str) - 木马描述信息

        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.GetUhostsecTrojanDescriptionRequestSchema().dumps(d)

        resp = self.invoke("GetUhostsecTrojanDescription", d, **kwargs)
        return apis.GetUhostsecTrojanDescriptionResponseSchema().loads(resp)

    def list_uhosts_ec_warn_days_statistics_v2(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """ListUHostsecWarnDaysStatisticsV2 - 获取按天列出各类告警统计值，但不统计暴力破解失败数据，SshBruteFailed为0

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_
        - **EndTime** (str) - 统计结束时间(y-m-d hh:mm:ss)。不填写默认为当前时间
        - **StartTime** (str) - 统计开始时间(y-m-d hh:mm:ss)。不填写默认从一周前开始统计

        **Response**

        - **Statistics** (list) - 见 **Statistics** 模型定义

        **Response Model**

        **Statistics**
        - **AbnormalLogin** (int) - 异常登录告警统计值
        - **BaseCheck** (int) - 安全基线检查告警统计值
        - **Date** (str) - 进行告警统计的时间
        - **SshBruteFailed** (int) - 暴力破解失败统计值
        - **SshBruteSucceeded** (int) - 暴力破解成功告警统计值
        - **Trojan** (int) - 木马告警统计值
        - **VulCheck** (int) - 漏洞检查告警统计值


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.ListUHostsecWarnDaysStatisticsV2RequestSchema().dumps(d)

        resp = self.invoke("ListUHostsecWarnDaysStatisticsV2", d, **kwargs)
        return apis.ListUHostsecWarnDaysStatisticsV2ResponseSchema().loads(resp)

    def list_uhosts_ec_warn_statistics_v2(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """ListUHostsecWarnStatisticsV2 - 获取当前账号与项目下的各类主机安全告警统计值，但不统计暴力破解失败数据，SshBruteFailed为0

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_

        **Response**

        - **WarnStatistics** (dict) - 见 **WarnStatistics** 模型定义

        **Response Model**

        **WarnStatistics**
        - **AbnormalLogin** (int) - 异常登录告警统计值
        - **BaseCheck** (int) - 安全基线检查告警统计值
        - **SshBruteFailed** (int) - 暴力破解失败统计值
        - **SshBruteSucceeded** (int) - 暴力破解成功告警统计值
        - **Trojan** (int) - 木马告警统计值
        - **VulCheck** (int) - 漏洞检查告警统计值


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.ListUHostsecWarnStatisticsV2RequestSchema().dumps(d)

        resp = self.invoke("ListUHostsecWarnStatisticsV2", d, **kwargs)
        return apis.ListUHostsecWarnStatisticsV2ResponseSchema().loads(resp)

    def list_uhostsec_common_login_ip(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """ListUhostsecCommonLoginIp - 列出公共登录ip列表

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_

        **Response**

        - **Infos** (list) - 见 **IP** 模型定义

        **Response Model**

        **IP**
        - **Account** (str) - 操作账号
        - **CreateTime** (str) - 添加时间
        - **ID** (str) - ID
        - **IP** (str) - IP


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.ListUhostsecCommonLoginIpRequestSchema().dumps(d)

        resp = self.invoke("ListUhostsecCommonLoginIp", d, **kwargs)
        return apis.ListUhostsecCommonLoginIpResponseSchema().loads(resp)

    def list_uhostsec_common_login_location(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """ListUhostsecCommonLoginLocation - 获取公共登录地列表

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_

        **Response**

        - **Infos** (list) - 见 **CommonLoginLocationInfo** 模型定义

        **Response Model**

        **CommonLoginLocationInfo**
        - **Account** (str) - 账号
        - **City** (str) - 城市
        - **Country** (str) - 国家
        - **CreateTime** (str) - 创建/修改时间
        - **Province** (str) - 省份


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.ListUhostsecCommonLoginLocationRequestSchema().dumps(d)

        resp = self.invoke("ListUhostsecCommonLoginLocation", d, **kwargs)
        return apis.ListUhostsecCommonLoginLocationResponseSchema().loads(resp)

    def opt_business_ver_auto(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """OptBusinessVerAuto - 对自动设置企业版的开关设置

        **Request**

        - **ProjectId** (str) - (Config) 项目ID
        - **Open** (bool) - (Required) 开(true)/关(false)

        **Response**

        - **OpenStatus** (bool) - 当前开关状态，false-关闭，true-开启

        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.OptBusinessVerAutoRequestSchema().dumps(d)

        resp = self.invoke("OptBusinessVerAuto", d, **kwargs)
        return apis.OptBusinessVerAutoResponseSchema().loads(resp)

    def opt_pay_auto_renew(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """OptPayAutoRenew - 自动续费功能的开关

        **Request**

        - **ProjectId** (str) - (Config) 项目ID
        - **Open** (bool) - (Required) 开(true)/关(false)

        **Response**

        - **OpenStatus** (bool) - 当前开关状态，false-关闭，true-开启

        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.OptPayAutoRenewRequestSchema().dumps(d)

        resp = self.invoke("OptPayAutoRenew", d, **kwargs)
        return apis.OptPayAutoRenewResponseSchema().loads(resp)

    def query_bill_point_deduction_flow_by_cycle(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """QueryBillPointDeductionFlowByCycle - 按照周期(目前只支持按天)统计用户计费点数变化(增加/减少/预留)情况

        **Request**

        - **ProjectId** (str) - (Config) 项目ID
        - **Type** (str) - (Required) 周期(可用值:day)
        - **EndTime** (str) - (可选)查询结束时间，格式xxxx-xx-xx
        - **StartTime** (str) - (可选)查询开始时间，格式xxxx-xx-xx

        **Response**

        - **Result** (list) - 见 **CycleBillPointStat** 模型定义

        **Response Model**

        **CycleBillPointStat**
        - **AddPointNum** (int) - 减少的减少
        - **RemainPointNum** (int) - 余留的点数
        - **SubPointNum** (int) - 增加的点数
        - **Time** (str) - 统计时间


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.QueryBillPointDeductionFlowByCycleRequestSchema().dumps(d)

        resp = self.invoke("QueryBillPointDeductionFlowByCycle", d, **kwargs)
        return apis.QueryBillPointDeductionFlowByCycleResponseSchema().loads(
            resp
        )

    def query_newest_update_time(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """QueryNewestUpdateTime - 查询下载数据最新更新时间

        **Request**

        - **ProjectId** (str) - (Config) 项目ID

        **Response**

        - **Result** (dict) - 见 **DataSignatureNewestUpdateTime** 模型定义

        **Response Model**

        **DataSignatureNewestUpdateTime**
        - **Login** (str) - 登录流水最新更新时间
        - **Torojan** (str) - 木马样本最新更新时间
        - **Vul** (str) - 漏洞最新更新时间
        - **WebBase** (str) - web基线最新更新时间
        - **Webshell** (str) - Webshell最新更新时间


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.QueryNewestUpdateTimeRequestSchema().dumps(d)

        resp = self.invoke("QueryNewestUpdateTime", d, **kwargs)
        return apis.QueryNewestUpdateTimeResponseSchema().loads(resp)

    def query_pay_info(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """QueryPayInfo - 查询用户的付费信息，保护目前未消费点数，点数过期时间，自动续费开关等

        **Request**

        - **ProjectId** (str) - (Config) 项目ID

        **Response**

        - **AutoBusinessVer** (bool) - 自动企业版开关
        - **AutoRenew** (bool) - 自动续费开关
        - **BillPoint** (int) - 未消费预付费点数
        - **CompanyId** (int) - 公司ID
        - **ExpiratTime** (str) - 预付费点数过期时间
        - **OrganizationId** (int) - 项目ID
        - **RemainTime** (str) - 预付费点数剩余使用时长
        - **RenewPointNum** (int) - 用户最近一次购买的点数大小
        - **ResourceLongId** (str) - 资源ID
        - **UpdateTime** (str) - 更改时间

        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.QueryPayInfoRequestSchema().dumps(d)

        resp = self.invoke("QueryPayInfo", d, **kwargs)
        return apis.QueryPayInfoResponseSchema().loads(resp)

    def query_uhost_sec_warning_base_checks(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """QueryUHostSecWarningBaseChecks - 查询正在告警的安全基线类型列表

        **Request**

        - **ProjectId** (str) - (Config) 项目ID。不填写为默认项目，子帐号必须填写。 请参考 `GetProjectList接口 <https://docs.ucloud.cn/api/summary/get_project_list>`_
        - **Type** (str) - (Required) 过滤BaseCheck告警类型，sys:系统安全检查，app:应用安全检查

        **Response**

        - **Result** (list) - 见 **BaseCheckWarning** 模型定义

        **Response Model**

        **BaseCheckWarning**
        - **AgentCount** (int) - 影响主机数
        - **AppName** (str) - 应用类
        - **Description** (str) - 风险描述
        - **DescriptionEn** (str) - 风险英文描述
        - **RiskLevel** (str) - 风险等级
        - **RiskType** (str) - 风险类型
        - **RuleID** (str) - 基线规则ID


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.QueryUHostSecWarningBaseChecksRequestSchema().dumps(d)

        resp = self.invoke("QueryUHostSecWarningBaseChecks", d, **kwargs)
        return apis.QueryUHostSecWarningBaseChecksResponseSchema().loads(resp)

    def query_week_report_list(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """QueryWeekReportList - 查询主机安全周报

        **Request**

        - **ProjectId** (str) - (Config) 项目ID
        - **PageIndex** (int) - 第N页
        - **PageSize** (int) - 页大小

        **Response**

        - **Result** (list) - 见 **WeekReport** 模型定义
        - **Total** (int) - 记录总数

        **Response Model**

        **WeekReport**
        - **FileName** (str) - 文件名称


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.QueryWeekReportListRequestSchema().dumps(d)

        resp = self.invoke("QueryWeekReportList", d, **kwargs)
        return apis.QueryWeekReportListResponseSchema().loads(resp)

    def switch_agent_function_version(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """SwitchAgentFunctionVersion - 对agent在各个功能版本之间切换

        **Request**

        - **ProjectId** (str) - (Config) 项目ID
        - **AgentList** (str) - (Required) 操作的Agent列表，以逗号分隔，如全部则设成ALL
        - **ChargeType** (int) - (Required) 付费类型 月付或年付
        - **FuncVersion** (int) - (Required) 功能版本(0-基础版 1-企业版)
        - **Coupon** (str) - 代金券
        - **Quantity** (int) - 购买数量

        **Response**

        - **Records** (dict) - 见 **SwitchAgentRecord** 模型定义

        **Response Model**

        **SwitchAgentRecord**
        - **AgentID** (str) -
        - **Message** (str) -
        - **RetCode** (int) -


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.SwitchAgentFunctionVersionRequestSchema().dumps(d)

        resp = self.invoke("SwitchAgentFunctionVersion", d, **kwargs)
        return apis.SwitchAgentFunctionVersionResponseSchema().loads(resp)

    def vul_statistic_top_n(
        self, req: typing.Optional[dict] = None, **kwargs
    ) -> dict:
        """VulStatisticTopN - 某种类型漏洞存在主机的主机数TOP N

        **Request**

        - **ProjectId** (str) - (Config) 项目ID
        - **TopN** (int) - 感染主机数量最多的前N个漏洞，最小为10

        **Response**

        - **Result** (list) - 见 **VulStatisticTopNInfo** 模型定义

        **Response Model**

        **VulStatisticTopNInfo**
        - **AgentCount** (int) - 存在该漏洞的主机数
        - **Name** (str) - 漏洞名称
        - **VulID** (str) - 漏洞ID


        """
        # build request
        d = {
            "ProjectId": self.config.project_id,
        }
        req and d.update(req)
        d = apis.VulStatisticTopNRequestSchema().dumps(d)

        resp = self.invoke("VulStatisticTopN", d, **kwargs)
        return apis.VulStatisticTopNResponseSchema().loads(resp)
