""" Code is generated by ucloud-model, DO NOT EDIT IT. """

from ucloud.core.typesystem import schema, fields


class CreateUClickhouseClusterResponseDataSchema(schema.ResponseSchema):
    """CreateUClickhouseClusterResponseData -"""

    fields = {
        "ClusterId": fields.Str(required=True, load_from="ClusterId"),
    }


class ClickhouseNodeSchema(schema.ResponseSchema):
    """ClickhouseNode -"""

    fields = {
        "CPU": fields.Int(required=True, load_from="CPU"),
        "ClusterId": fields.Str(required=True, load_from="ClusterId"),
        "CreateTimestamp": fields.Int(
            required=True, load_from="CreateTimestamp"
        ),
        "DataDiskSize": fields.Int(required=True, load_from="DataDiskSize"),
        "DataDiskType": fields.Str(required=True, load_from="DataDiskType"),
        "IPv4": fields.Str(required=True, load_from="IPv4"),
        "MachineType": fields.Str(required=True, load_from="MachineType"),
        "Memory": fields.Int(required=True, load_from="Memory"),
        "NodeId": fields.Str(required=True, load_from="NodeId"),
        "NodeName": fields.Str(required=True, load_from="NodeName"),
        "ResourceId": fields.Str(required=True, load_from="ResourceId"),
        "ServiceStatus": fields.Str(required=True, load_from="ServiceStatus"),
        "ShardGroup": fields.Str(required=True, load_from="ShardGroup"),
        "SysDiskSize": fields.Int(required=True, load_from="SysDiskSize"),
        "SysDiskType": fields.Str(required=True, load_from="SysDiskType"),
        "Zone": fields.Str(required=True, load_from="Zone"),
    }


class ClickhouseClusterSchema(schema.ResponseSchema):
    """ClickhouseCluster -"""

    fields = {
        "ClickhouseDataDiskSize": fields.Int(
            required=True, load_from="ClickhouseDataDiskSize"
        ),
        "ClickhouseDataDiskType": fields.Str(
            required=True, load_from="ClickhouseDataDiskType"
        ),
        "ClickhouseMachineTypeId": fields.Str(
            required=True, load_from="ClickhouseMachineTypeId"
        ),
        "ClickhouseMachineTypeName": fields.Str(
            required=True, load_from="ClickhouseMachineTypeName"
        ),
        "ClickhouseNodeCPU": fields.Int(
            required=True, load_from="ClickhouseNodeCPU"
        ),
        "ClickhouseNodeMemory": fields.Int(
            required=True, load_from="ClickhouseNodeMemory"
        ),
        "ClickhouseVersion": fields.Str(
            required=True, load_from="ClickhouseVersion"
        ),
        "ClusterId": fields.Str(required=True, load_from="ClusterId"),
        "ClusterName": fields.Str(required=True, load_from="ClusterName"),
        "CreateTimestamp": fields.Int(
            required=True, load_from="CreateTimestamp"
        ),
        "ExpireTimestamp": fields.Float(
            required=True, load_from="ExpireTimestamp"
        ),
        "IsBackup": fields.Str(required=True, load_from="IsBackup"),
        "IsSecgroup": fields.Str(required=True, load_from="IsSecgroup"),
        "IsTieredStorage": fields.Str(
            required=True, load_from="IsTieredStorage"
        ),
        "IsZookeeperHA": fields.Str(required=True, load_from="IsZookeeperHA"),
        "MachineType": fields.Str(required=True, load_from="MachineType"),
        "MultiZones": fields.List(fields.Str()),
        "OrganizationId": fields.Int(required=True, load_from="OrganizationId"),
        "RegionId": fields.Int(required=True, load_from="RegionId"),
        "ReplicateCount": fields.Int(required=True, load_from="ReplicateCount"),
        "ShardCount": fields.Int(required=True, load_from="ShardCount"),
        "Status": fields.Str(required=True, load_from="Status"),
        "SubnetId": fields.Str(required=True, load_from="SubnetId"),
        "TopOrganizationId": fields.Int(
            required=True, load_from="TopOrganizationId"
        ),
        "VPCId": fields.Str(required=True, load_from="VPCId"),
        "ZookeeperDataDiskSize": fields.Int(
            required=True, load_from="ZookeeperDataDiskSize"
        ),
        "ZookeeperDataDiskType": fields.Str(
            required=True, load_from="ZookeeperDataDiskType"
        ),
        "ZookeeperMachineTypeId": fields.Str(
            required=True, load_from="ZookeeperMachineTypeId"
        ),
        "ZookeeperMachineTypeName": fields.Str(
            required=True, load_from="ZookeeperMachineTypeName"
        ),
        "ZookeeperNodeCPU": fields.Int(
            required=True, load_from="ZookeeperNodeCPU"
        ),
        "ZookeeperNodeMemory": fields.Int(
            required=True, load_from="ZookeeperNodeMemory"
        ),
        "ZookeeperVersion": fields.Str(
            required=True, load_from="ZookeeperVersion"
        ),
    }


class PaymentSchema(schema.ResponseSchema):
    """Payment -"""

    fields = {
        "ChargeType": fields.Str(required=True, load_from="ChargeType"),
        "CreateTimestamp": fields.Int(
            required=True, load_from="CreateTimestamp"
        ),
        "ExpireTimestamp": fields.Int(
            required=True, load_from="ExpireTimestamp"
        ),
        "OriginalPrice": fields.Int(required=True, load_from="OriginalPrice"),
        "Price": fields.Int(required=True, load_from="Price"),
        "ResourceId": fields.Str(required=True, load_from="ResourceId"),
    }


class ZookeeperNodeSchema(schema.ResponseSchema):
    """ZookeeperNode -"""

    fields = {
        "CPU": fields.Int(required=True, load_from="CPU"),
        "ClusterId": fields.Str(required=True, load_from="ClusterId"),
        "CreateTimestamp": fields.Int(
            required=True, load_from="CreateTimestamp"
        ),
        "DataDiskSize": fields.Int(required=True, load_from="DataDiskSize"),
        "DataDiskType": fields.Str(required=True, load_from="DataDiskType"),
        "MachineType": fields.Str(required=True, load_from="MachineType"),
        "Memory": fields.Int(required=True, load_from="Memory"),
        "NodeId": fields.Str(required=True, load_from="NodeId"),
        "NodeName": fields.Str(required=True, load_from="NodeName"),
        "ResourceId": fields.Str(required=True, load_from="ResourceId"),
        "ServiceStatus": fields.Str(required=True, load_from="ServiceStatus"),
        "SysDiskSize": fields.Int(required=True, load_from="SysDiskSize"),
        "SysDiskType": fields.Str(required=True, load_from="SysDiskType"),
        "Zone": fields.Str(required=True, load_from="Zone"),
        "ZookeeperMyId": fields.Str(required=True, load_from="ZookeeperMyId"),
    }


class DescribeUClickhouseClusterResponseDataSchema(schema.ResponseSchema):
    """DescribeUClickhouseClusterResponseData -"""

    fields = {
        "ClickhouseNodes": fields.List(ClickhouseNodeSchema()),
        "Cluster": ClickhouseClusterSchema(),
        "Payment": PaymentSchema(),
        "ZookeeperNodes": fields.List(ZookeeperNodeSchema()),
    }


class ClickhouseDataDiskSchema(schema.ResponseSchema):
    """ClickhouseDataDisk -"""

    fields = {
        "DefaultDataDiskSize": fields.Int(
            required=True, load_from="DefaultDataDiskSize"
        ),
        "DiskType": fields.Str(required=True, load_from="DiskType"),
        "MaxDiskSize": fields.Int(required=True, load_from="MaxDiskSize"),
        "MinDiskSize": fields.Int(required=True, load_from="MinDiskSize"),
        "Step": fields.Int(required=True, load_from="Step"),
    }


class ClickhouseMachineTypeOptionSchema(schema.ResponseSchema):
    """ClickhouseMachineTypeOption -"""

    fields = {
        "CPU": fields.Int(required=True, load_from="CPU"),
        "ClickhouseMachineTypeId": fields.Str(
            required=True, load_from="ClickhouseMachineTypeId"
        ),
        "DataDisks": fields.List(ClickhouseDataDiskSchema()),
        "MachineType": fields.Str(required=True, load_from="MachineType"),
        "Memory": fields.Int(required=True, load_from="Memory"),
        "NodeCounts": fields.List(fields.Int()),
    }


class ClickhouseMachineTypeSchema(schema.ResponseSchema):
    """ClickhouseMachineType -"""

    fields = {
        "ClickhouseMachineTypeName": fields.Str(
            required=True, load_from="ClickhouseMachineTypeName"
        ),
        "ClickhouseMachineTypeOptions": fields.List(
            ClickhouseMachineTypeOptionSchema()
        ),
        "IsSecgroupMachineType": fields.Str(
            required=True, load_from="IsSecgroupMachineType"
        ),
    }


class ClickhouseVersionSchema(schema.ResponseSchema):
    """ClickhouseVersion -"""

    fields = {
        "Version": fields.Str(required=True, load_from="Version"),
        "VersionName": fields.Str(required=True, load_from="VersionName"),
    }


class GetCreateUClickhouseClusterOptionResponseDataSchema(
    schema.ResponseSchema
):
    """GetCreateUClickhouseClusterOptionResponseData -"""

    fields = {
        "ClickhouseMachineTypes": fields.List(ClickhouseMachineTypeSchema()),
        "ClickhouseVersions": fields.List(ClickhouseVersionSchema()),
        "MaxNodeCount": fields.Int(required=True, load_from="MaxNodeCount"),
        "ZookeeperMachineTypes": fields.List(ClickhouseMachineTypeSchema()),
    }


class ListUClickhouseClusterResponseDataSchema(schema.ResponseSchema):
    """ListUClickhouseClusterResponseData -"""

    fields = {
        "Clusters": ClickhouseClusterSchema(),
        "TotalCount": fields.Int(required=True, load_from="TotalCount"),
    }
