""" Code is generated by ucloud-model, DO NOT EDIT IT. """

from ucloud.core.typesystem import schema, fields
from ucloud.services.nlb.schemas import models

""" NLB API Schema
"""


"""
API: AddNLBTargets

给监听器添加后端服务节点
"""


class AddNLBTargetsParamTargetsSchema(schema.RequestSchema):
    """AddNLBTargetsParamTargets -"""

    fields = {
        "Enabled": fields.Bool(required=False, dump_to="Enabled"),
        "Port": fields.Int(required=False, dump_to="Port"),
        "Region": fields.Str(required=False, dump_to="Region"),
        "ResourceIP": fields.Str(required=False, dump_to="ResourceIP"),
        "ResourceId": fields.Str(required=False, dump_to="ResourceId"),
        "ResourceName": fields.Str(required=False, dump_to="ResourceName"),
        "ResourceType": fields.Str(required=False, dump_to="ResourceType"),
        "SubnetId": fields.Str(required=False, dump_to="SubnetId"),
        "VPCId": fields.Str(required=False, dump_to="VPCId"),
        "Weight": fields.Int(required=False, dump_to="Weight"),
    }


class AddNLBTargetsRequestSchema(schema.RequestSchema):
    """AddNLBTargets - 给监听器添加后端服务节点"""

    fields = {
        "ListenerId": fields.Str(required=True, dump_to="ListenerId"),
        "NLBId": fields.Str(required=True, dump_to="NLBId"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Region": fields.Str(required=True, dump_to="Region"),
        "Targets": fields.List(AddNLBTargetsParamTargetsSchema()),
    }


class AddNLBTargetsResponseSchema(schema.ResponseSchema):
    """AddNLBTargets - 给监听器添加后端服务节点"""

    fields = {
        "Targets": fields.List(
            models.TargetSchema(), required=True, load_from="Targets"
        ),
    }


"""
API: CreateNLBListener

创建监听器
"""


class CreateNLBListenerParamHealthCheckConfigSchema(schema.RequestSchema):
    """CreateNLBListenerParamHealthCheckConfig -"""

    fields = {
        "Enabled": fields.Bool(required=False, dump_to="Enabled"),
        "Port": fields.Int(required=True, dump_to="Port"),
        "ReqMsg": fields.Str(required=False, dump_to="ReqMsg"),
        "ResMsg": fields.Str(required=False, dump_to="ResMsg"),
        "Type": fields.Str(required=False, dump_to="Type"),
    }


class CreateNLBListenerRequestSchema(schema.RequestSchema):
    """CreateNLBListener - 创建监听器"""

    fields = {
        "EndPort": fields.Int(required=False, dump_to="EndPort"),
        "ForwardSrcIPMethod": fields.Str(
            required=False, dump_to="ForwardSrcIPMethod"
        ),
        "HealthCheckConfig": CreateNLBListenerParamHealthCheckConfigSchema(
            required=False, dump_to="HealthCheckConfig"
        ),
        "NLBId": fields.Str(required=True, dump_to="NLBId"),
        "Name": fields.Str(required=False, dump_to="Name"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Protocol": fields.Str(required=True, dump_to="Protocol"),
        "Region": fields.Str(required=True, dump_to="Region"),
        "Remark": fields.Str(required=False, dump_to="Remark"),
        "Scheduler": fields.Str(required=False, dump_to="Scheduler"),
        "StartPort": fields.Int(required=False, dump_to="StartPort"),
        "StickinessTimeout": fields.Int(
            required=False, dump_to="StickinessTimeout"
        ),
    }


class CreateNLBListenerResponseSchema(schema.ResponseSchema):
    """CreateNLBListener - 创建监听器"""

    fields = {
        "ListenerId": fields.Str(required=True, load_from="ListenerId"),
    }


"""
API: CreateNetworkLoadBalancer

创建网络型负载均衡
"""


class CreateNetworkLoadBalancerRequestSchema(schema.RequestSchema):
    """CreateNetworkLoadBalancer - 创建网络型负载均衡"""

    fields = {
        "ApiVersion": fields.Str(required=False, dump_to="ApiVersion"),
        "ChargeType": fields.Str(required=False, dump_to="ChargeType"),
        "CouponId": fields.Str(required=False, dump_to="CouponId"),
        "IPVersion": fields.Str(required=False, dump_to="IPVersion"),
        "Name": fields.Str(required=False, dump_to="Name"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Quantity": fields.Int(required=False, dump_to="Quantity"),
        "Region": fields.Str(required=True, dump_to="Region"),
        "Remark": fields.Str(required=False, dump_to="Remark"),
        "SubnetId": fields.Str(required=True, dump_to="SubnetId"),
        "Tag": fields.Str(required=False, dump_to="Tag"),
        "VPCId": fields.Str(required=True, dump_to="VPCId"),
    }


class CreateNetworkLoadBalancerResponseSchema(schema.ResponseSchema):
    """CreateNetworkLoadBalancer - 创建网络型负载均衡"""

    fields = {
        "Message": fields.Str(required=True, load_from="Message"),
        "NLBId": fields.Str(required=True, load_from="NLBId"),
    }


"""
API: DeleteNLBListener

删除一个网络型负载均衡监听器
"""


class DeleteNLBListenerRequestSchema(schema.RequestSchema):
    """DeleteNLBListener - 删除一个网络型负载均衡监听器"""

    fields = {
        "ListenerId": fields.Str(required=True, dump_to="ListenerId"),
        "NLBId": fields.Str(required=True, dump_to="NLBId"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Region": fields.Str(required=True, dump_to="Region"),
    }


class DeleteNLBListenerResponseSchema(schema.ResponseSchema):
    """DeleteNLBListener - 删除一个网络型负载均衡监听器"""

    fields = {}


"""
API: DeleteNetworkLoadBalancer

删除负载均衡实例
"""


class DeleteNetworkLoadBalancerRequestSchema(schema.RequestSchema):
    """DeleteNetworkLoadBalancer - 删除负载均衡实例"""

    fields = {
        "NLBId": fields.Str(required=True, dump_to="NLBId"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Region": fields.Str(required=True, dump_to="Region"),
        "ReleaseEIP": fields.Bool(required=False, dump_to="ReleaseEIP"),
    }


class DeleteNetworkLoadBalancerResponseSchema(schema.ResponseSchema):
    """DeleteNetworkLoadBalancer - 删除负载均衡实例"""

    fields = {}


"""
API: DescribeNLBListeners

描述监听器
"""


class DescribeNLBListenersRequestSchema(schema.RequestSchema):
    """DescribeNLBListeners - 描述监听器"""

    fields = {
        "Limit": fields.Int(required=False, dump_to="Limit"),
        "ListenerId": fields.Str(required=False, dump_to="ListenerId"),
        "NLBId": fields.Str(required=True, dump_to="NLBId"),
        "Offset": fields.Int(required=False, dump_to="Offset"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Region": fields.Str(required=True, dump_to="Region"),
    }


class DescribeNLBListenersResponseSchema(schema.ResponseSchema):
    """DescribeNLBListeners - 描述监听器"""

    fields = {
        "Listeners": fields.List(
            models.ListenerSchema(), required=True, load_from="Listeners"
        ),
        "TotalCount": fields.Int(required=True, load_from="TotalCount"),
    }


"""
API: DescribeNetworkLoadBalancers

描述负载均衡实例
"""


class DescribeNetworkLoadBalancersRequestSchema(schema.RequestSchema):
    """DescribeNetworkLoadBalancers - 描述负载均衡实例"""

    fields = {
        "Limit": fields.Int(required=False, dump_to="Limit"),
        "NLBIds": fields.List(fields.Str()),
        "Offset": fields.Int(required=False, dump_to="Offset"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Region": fields.Str(required=True, dump_to="Region"),
        "ShowDetail": fields.Bool(required=False, dump_to="ShowDetail"),
        "SubnetId": fields.Str(required=False, dump_to="SubnetId"),
        "VPCId": fields.Str(required=False, dump_to="VPCId"),
    }


class DescribeNetworkLoadBalancersResponseSchema(schema.ResponseSchema):
    """DescribeNetworkLoadBalancers - 描述负载均衡实例"""

    fields = {
        "NLBs": fields.List(
            models.NetworkLoadBalancerSchema(), required=True, load_from="NLBs"
        ),
        "TotalCount": fields.Int(required=True, load_from="TotalCount"),
    }


"""
API: GetNetworkLoadBalancerPrice

获取负载均衡价格
"""


class GetNetworkLoadBalancerPriceRequestSchema(schema.RequestSchema):
    """GetNetworkLoadBalancerPrice - 获取负载均衡价格"""

    fields = {
        "ChargeType": fields.Str(required=False, dump_to="ChargeType"),
        "PayMode": fields.Str(required=False, dump_to="PayMode"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Quantity": fields.Int(required=False, dump_to="Quantity"),
        "Region": fields.Str(required=True, dump_to="Region"),
    }


class GetNetworkLoadBalancerPriceResponseSchema(schema.ResponseSchema):
    """GetNetworkLoadBalancerPrice - 获取负载均衡价格"""

    fields = {
        "Prices": fields.List(
            models.PriceDetailSchema(), required=True, load_from="Prices"
        ),
    }


"""
API: RemoveNLBTargets

删除后端服务节点
"""


class RemoveNLBTargetsRequestSchema(schema.RequestSchema):
    """RemoveNLBTargets - 删除后端服务节点"""

    fields = {
        "Ids": fields.List(fields.Str()),
        "ListenerId": fields.Str(required=True, dump_to="ListenerId"),
        "NLBId": fields.Str(required=True, dump_to="NLBId"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Region": fields.Str(required=True, dump_to="Region"),
    }


class RemoveNLBTargetsResponseSchema(schema.ResponseSchema):
    """RemoveNLBTargets - 删除后端服务节点"""

    fields = {}


"""
API: UpdateNLBListenerAttribute

更新监听器属性
"""


class UpdateNLBListenerAttributeParamHealthCheckConfigSchema(
    schema.RequestSchema
):
    """UpdateNLBListenerAttributeParamHealthCheckConfig -"""

    fields = {
        "Enabled": fields.Bool(required=False, dump_to="Enabled"),
        "Port": fields.Int(required=False, dump_to="Port"),
        "ReqMsg": fields.Str(required=False, dump_to="ReqMsg"),
        "ResMsg": fields.Str(required=False, dump_to="ResMsg"),
        "Type": fields.Str(required=False, dump_to="Type"),
    }


class UpdateNLBListenerAttributeRequestSchema(schema.RequestSchema):
    """UpdateNLBListenerAttribute - 更新监听器属性"""

    fields = {
        "EndPort": fields.Int(required=False, dump_to="EndPort"),
        "ForwardSrcIPMethod": fields.Str(
            required=False, dump_to="ForwardSrcIPMethod"
        ),
        "HealthCheckConfig": UpdateNLBListenerAttributeParamHealthCheckConfigSchema(
            required=False, dump_to="HealthCheckConfig"
        ),
        "ListenerId": fields.Str(required=True, dump_to="ListenerId"),
        "NLBId": fields.Str(required=True, dump_to="NLBId"),
        "Name": fields.Str(required=False, dump_to="Name"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Region": fields.Str(required=True, dump_to="Region"),
        "Remark": fields.Str(required=False, dump_to="Remark"),
        "Scheduler": fields.Str(required=False, dump_to="Scheduler"),
        "StartPort": fields.Int(required=False, dump_to="StartPort"),
        "StickinessTimeout": fields.Int(
            required=False, dump_to="StickinessTimeout"
        ),
    }


class UpdateNLBListenerAttributeResponseSchema(schema.ResponseSchema):
    """UpdateNLBListenerAttribute - 更新监听器属性"""

    fields = {}


"""
API: UpdateNLBTargetsAttribute

更新后端服务节点属性
"""


class UpdateNLBTargetsAttributeParamTargetsSchema(schema.RequestSchema):
    """UpdateNLBTargetsAttributeParamTargets -"""

    fields = {
        "Enabled": fields.Bool(required=False, dump_to="Enabled"),
        "Id": fields.Str(required=False, dump_to="Id"),
        "Weight": fields.Int(required=False, dump_to="Weight"),
    }


class UpdateNLBTargetsAttributeRequestSchema(schema.RequestSchema):
    """UpdateNLBTargetsAttribute - 更新后端服务节点属性"""

    fields = {
        "ListenerId": fields.Str(required=True, dump_to="ListenerId"),
        "NLBId": fields.Str(required=True, dump_to="NLBId"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Region": fields.Str(required=True, dump_to="Region"),
        "Targets": fields.List(UpdateNLBTargetsAttributeParamTargetsSchema()),
    }


class UpdateNLBTargetsAttributeResponseSchema(schema.ResponseSchema):
    """UpdateNLBTargetsAttribute - 更新后端服务节点属性"""

    fields = {}


"""
API: UpdateNetworkLoadBalancerAttribute

更新负载均衡实例属性
"""


class UpdateNetworkLoadBalancerAttributeRequestSchema(schema.RequestSchema):
    """UpdateNetworkLoadBalancerAttribute - 更新负载均衡实例属性"""

    fields = {
        "NLBId": fields.Str(required=True, dump_to="NLBId"),
        "Name": fields.Str(required=False, dump_to="Name"),
        "ProjectId": fields.Str(required=False, dump_to="ProjectId"),
        "Region": fields.Str(required=True, dump_to="Region"),
        "Remark": fields.Str(required=False, dump_to="Remark"),
        "Tag": fields.Str(required=False, dump_to="Tag"),
    }


class UpdateNetworkLoadBalancerAttributeResponseSchema(schema.ResponseSchema):
    """UpdateNetworkLoadBalancerAttribute - 更新负载均衡实例属性"""

    fields = {}
